### ISSUE TITLE
Do you have plans to support this project or should I fork it and maintain that?

### ISSUE THREAD

**Issue by anotherhale** [iodevs/elm-modal#6]
I have a PR ready that adds support for handling `Cancel` events in addition to the close event.  I also would like to improve the CSS - I have an issue where my modal button is at the bottom of a long page but the modal displays 200 px from the top of the page.  I would like to add in some additional configuration to tweak and better support this.  Just don't know if you plan to maintain this project or if I should just fork this and then maintain that version?
It is a great project and I have not see any other Modal projects in the Elm community with this much flexibility.

**Comment by ondrej-tucek** [comment]
Hi @anotherhale 
thank you for your lovely words. That's great! Definitely add it here, no need new repo-library or fork for that... We'll add you as Collaborator with maintain role if you don't mind. Also don't hesitate with CR for us.
